### PR TITLE
3.0.1

### PR DESCRIPTION
**Pull request by andyfmiller**
- Add optional status description to outcomes v1 responses (e.g. ReadResultResponse).
- Add properly formatted body to outcomes v1 responses when status code != 200.
- Update version to 3.0.1.

### CODE REVIEW

**Review by xferra — APPROVED** [review]
LGTM.

I also noticed that release notes could be a little bit [more detailed](https://github.com/andyfmiller/LtiLibrary/compare/9db911ee980a23ef96b4846c220b7108596ac3a7...3.0.1).

PS: Do you want to continue with [Github Releases](https://github.com/andyfmiller/LtiLibrary/releases)?

**Comment by andyfmiller** [comment]
Added two more commits to pull request. Based on recommendations (most recently https://medium.com/bynder-tech/c-why-you-should-use-configureawait-false-in-your-library-code-d7837dce3d7f), I added ConfigureAwait(false) to the await calls within public async methods in both NetCore and AspNetCore libraries.

**Comment by andyfmiller** [comment]
RE: Github Releases, I try to remember to release when I publish to NuGet, but do forget sometimes. I haven't checked whether AppVeyor or Travis would automate that process.

RE: More detail, I agree. "Language usage." is not very helpful. Is "Add ConfigureAwait(false) to all await calls within public async methods in the AspNetCore library" better?

**Comment by xferra** [comment]
1) As for the releases, it could be pretty simple: publish every tag build to [GitHub releases](https://www.appveyor.com/docs/deployment/github/) and [Nuget feed](https://www.appveyor.com/docs/deployment/nuget/).
2) If approve only PRs with good messages/descriptions then it's possible to generate release notes with the tool like [that](https://github.com/GitTools/GitReleaseManager).

**Comment by andyfmiller** [comment]
I tried to automate publish on every tag build, but it seemed to get into a loop of building and publishing. Backed that out, but did experiment with manual publishing to both GitHub and NuGet. That worked, so I'll clear my head and try again later.

I'll also investigate GitReleaseManager. In the mean time, I've duplicated the NuGet release notes in the GitHub release notes, which--while hand written--are better than nothing.

**Pull request merged**
