### PR TITLE
Make AddBodyHashHeaderAttribute compatible with ASP.NET Core 2.1+

### PR DESCRIPTION
**Pull request by mdrgzi**
References:

[Re-reading ASP.Net Core request bodies with EnableBuffering(](https://devblogs.microsoft.com/aspnet/re-reading-asp-net-core-request-bodies-with-enablebuffering/))

[HTTP: Synchronous IO disabled in all servers](https://docs.microsoft.com/en-us/dotnet/core/compatibility/2.2-3.0#http-synchronous-io-disabled-in-all-servers)

[Add HashAlgorithm.ComputeHashAsync (.NET Core 5.0)](https://github.com/dotnet/corefx/pull/42565)

### CODE REVIEW

**Comment by srijken** [comment]
@mdrgzi (and others): how do you think about the .NET Core versioning? This PR makes it possible to have multiple builds side-by-side. 

I'm wondering if we shouldn't just target ASP.NET Core 3.1, and drop support for older versions. Reasoning:
* All versions except 3.1 are End of Support
* 3.1 is an LTS version

**Comment by mdrgzi** [comment]
Good question!

Based on [this How do I know...](https://github.com/dotnet/standard/blob/master/docs/versions.md#how-do-i-know-which-net-standard-version-i-should-target) and [this .NET Standard versions](https://dotnet.microsoft.com/platform/dotnet-standard#versions) I suggest to keep going with dotnet standard 2.0 only to get the best of both worlds.

**Comment by srijken** [comment]
Let's just keep the targeting the way it is now. NuGet packages contain netstandard16 and netstandard20, so this approach will just work.

Thanks!

**Comment by mdrgzi** [comment]
Even better. Thank you!

**Comment by srijken** [comment]
Just so you know, the nuget packages are in the GitHub package repository for now, waiting for #121

**Comment by srijken** [comment]
Just so you know, the nuget packages are in the GitHub package repository for now, waiting for #121

**Pull request merged**
