### PR TITLE
The fix of 'HttpResponse is not disposed #32' issue

### PR DESCRIPTION
**Pull request by valiukevich**

### CODE REVIEW

**Comment by xferra** [comment]
@valiukevich Please fix all merge conflicts, or probably we need to merge it in a separate brach (as far as #16 is still in progress).

**Comment by valiukevich** [comment]
This fix is not supposed to be merged on top of master. 
The latest version does not have this issue but ObjectDisposedException - other way around. 
This particilar fix should be used as hotfix for the version labeled 161 which should be on Nuget.

**Comment by andyfmiller** [comment]
I frankly do not know how to do what you are asking (merge into a previous point of master). And it feels like a lot of effort to hotfix the package on NuGet.

I discovered other problems with the package on NuGet when I started using @xferra's NET Core pull request. For example, the wrong type of header is being added to outcomes requests, and the content stream is disposed by the method that calculates outcomes signatures.

Would it be OK we wait for pull request #35 to be merged, then incorporate your changes, and then build a new package on NuGet?

**Comment by andyfmiller** [comment]
Closing this pull request now that the changes have also been incorporated into the v1.7.0 branch.

**Comment by xferra** [comment]
@andyfmiller May be it's a good time to think about 'feature branches'? I did some major changes in the scope of #16, so next time we can isolate them.

**Comment by andyfmiller** [comment]
Do you have a favorite description of feature branches that I can read? Are they like the "serialization-binder" branch in Newtonsoft.Json?

**Comment by xferra** [comment]
I can suggest this [article](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) (this is not my favorite one, but the explanation is quite good).

**Comment by andyfmiller** [comment]
I see. In a sense the v2.0.0 branch I just created is a feature branch. Is that right?

**Comment by xferra** [comment]
Yes! [it could be](http://semver.org) also interesting for you.

**Comment by andyfmiller** [comment]
A co-worker suggested semver.org too. If only because I want to remove obsolete methods (not to mention the renaming), a major version change seems appropriate.

**Comment by andyfmiller** [comment]
Have you used "git flow" to manage feature branches?

**Pull request closed without merging**
