### PR TITLE
Implement a way to specify HMAC-SHA256. Implements #22

### PR DESCRIPTION
**Pull request by srijken**
Implement a way for users of the library to use HMAC-SHA256 instead of the default HMAC-SHA1. Please comment/suggest if this is a workable solution.

### CODE REVIEW

**Comment by xferra** [comment]
Hello @srijken , thank you for your first contribution!
The proposed solution in general looks good, but I have 2 proposals/questions:
- You added support only for `SignatureMethodHmacSha256` but any string could be passed as param; probably `enum` is more suitable for that?
- Optional param `signatureMethod` was added to dozens of static methods. Probably we can avoid that: convert them to non-static inside a class which has a context (property or field) `signatureMethod `? (then we also can create a static instance of that class and execute methods it in the same way as now, etc.)

Please let me know what you think about it.

**Comment by srijken** [comment]
Good points, I'll look into both suggestions

**Comment by srijken** [comment]
@xferra I added the enum, seems cleaner already

I also thought about the static instance thing for a bit. I think it's prone to all kinds of threading related errors when we keep static (or static instance) state about the hashing algorithm, especially when interfacing as a consumer with multiple providers, or as provider with multiple clients that need different hashing algorithms.

Any suggestions on that?

**Comment by xferra** [comment]
Enum looks perfect, thanks!
As for your remark regarding static instance - completely agree, then I can only suggest converting all those classes to non-static - but it will affect public library API a lot.

I think this PR is good enough, ping @andyfmiller

**Comment by andyfmiller** [comment]
Looks good, but would you mind fixing the conflicts with the current master? 3.0.1 was merged in since you started this PR and it added ConfigureAwait(false) to all await calls within public async methods to avoid blocking if someone uses methodAsync().Result() instead of await methodAsyc.

Also, I'm wondering if you wanted to take on adding a few tests to LtiLibrary.NetCore.Tests/LtiRequestShould.cs?

**Comment by srijken** [comment]
Merged and extended existing tests

**Comment by andyfmiller** [comment]
Brilliant. Thank you!

**Pull request merged**
