### PR TITLE
Throw exception if required field is missing

### PR DESCRIPTION
**Pull request by andyfmiller**
For discussion. LtiRequest inspector examines an LtiRequest and reports on potential problems.

### CODE REVIEW

**Comment by xferra** [comment]
@andyfmiller this is actually PR #40 :)

**Comment by andyfmiller** [comment]
Trying a different approach...moved CheckForRequiredLtiParameters to LtiRequest so it can be used by both the TC (before launch) and TP (after parsing). See [SimpleLti.ConsumerController.Launch](https://github.com/andyfmiller/LtiSamples/blob/Issue39/SimpleLti/Controllers/ConsumerController.cs#L135-L139) and [SimpleLti.ProviderController.Tool](https://github.com/andyfmiller/LtiSamples/blob/Issue39/SimpleLti/Controllers/ProviderController.cs#L30-L33) for example.

If this seems like a better approach than the Inspector, then I'll add something like CheckForRequiredOutcomes1Parameters and CheckForRequiredOutcomes2Parameters. The application developer will be able to skip these checks, but the sample could all be updated to use them as a best practice.

What do you think?

**Comment by andyfmiller** [comment]
Here is a link to the new [CheckForRequiredLtiParameters](https://github.com/andyfmiller/LtiLibrary/blob/Issue39/LtiLibrary.Core/Lti1/LtiRequest.cs#L2331-L2384) method.

**Comment by xferra** [comment]
@andyfmiller looks good for me.

**Comment by andyfmiller** [comment]
Moved to NetCore source.

**Pull request closed without merging**
