### PR TITLE
Publish v2.0.0 to NuGet

### PR DESCRIPTION
**Pull request by andyfmiller**
The current release on NuGet is 1.6.1. Several major changes have been made since then:

1. Major rewrite to support NetCore
2. Add support for multiple targets
3. Rename async methods
4. Dispose outcome responses when done
5. Add Exception property to Outcomes2 response
6. Update assembly versions
7. Synchronize packages and project references between .csproj, packages.config, and project.json
8. Apply ReSharper code improvements such as eliminating unused usings and references, and simplifying syntax
9. Include all targets in the NuGet package

### CODE REVIEW

**Comment by andyfmiller** [comment]
@xferra I'd like to include all the targets you added into the NuGet package. Since I've never done this before, I'm using [this ](http://brian-federici.com/blog/2013/4/17/automatically-target-multiple-frameworks-in-your-nuget-package) as a reference. Please let me know if you have any tips.

**Comment by xferra** [comment]
@andyfmiller I should say that I don't own any nuget package, but as far as I know the publishing mechanism is al little [bit different](https://docs.microsoft.com/en-us/dotnet/articles/core/deploying/creating-nuget-packages) now. The only thing that you should do - is to mention your targets in the `project.json` file (and it will be changed to .csproj format soon again as I mentioned in #16 ([link](https://blogs.msdn.microsoft.com/dotnet/2016/10/19/net-core-tooling-in-visual-studio-15/)))

**Comment by andyfmiller** [comment]
_dotnet pack_ will work fine. I have a little testing left. Do you see anything worrisome in this pull request?

**Comment by xferra** [comment]
@andyfmiller Looks good for me!

**Pull request merged**
