### PR TITLE
In HttpResponseExtensions, encode the parameters

### PR DESCRIPTION
**Pull request by cadi3s**
The value of a parameter can contain characters that break the HTML form post.
E.g. a single quote in lis_person_name_full = "d'Artagnan", would cause a form post with input value="d".
NB I tested my fix on an older version of the LtiLibrary, so I did not actually compile and test my proposed change - sorry for that.

### CODE REVIEW

**Comment by willwm** [comment]
@cadi3s Thank you for your contribution! Unfortunately, as you noted, the change does not compile, but a simple change should get it working:

Replace this:
`HttpContext.Current.Server.HtmlEncode(request.Parameters[key])`

...with this:
`System.Net.WebUtility.HtmlEncode(request.Parameters[key])`

**Comment by cadi3s** [comment]
Thanks for the suggestion, I updated the code change and it builds now.
I was hoping you could confirm it is indeed a necessary fix.. I find it a bit scary to make an update to code that worked fine for so long, especially on Lti parameters after the hash has already been made. But it does fix my problem with characters like ' " < >, and it does work on https://lti.tools/saltire/tp

**Comment by andyfmiller** [comment]
I'll check it out this weekend. It looks like you found a legitimate bug.

**Comment by andyfmiller** [comment]
Thank you!

**Pull request merged**
